[build]
	base = "apps/frontend"
  publish = "dist" 
	command = "pnpm install --no-frozen-lockfile && turbo run build --filter frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
